micronaut:
  application:
    name: trip
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/trip`}
    username: ${JDBC_USER:trip}
    password: ${JDBC_PASSWORD:tripPWD}
    schema-generate: CREATE_UPDATE
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan: 'org.aliabdi.trip.core.data'
    properties:
      hibernate:
        hbm2ddl:
          auto: none

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

netty:
  default:
    allocator:
      max-order: 3
